name: hello-workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from the first job!"
      - name: Print current user
        run: whoami
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Say after first job
        run: echo "This is the second job running after the first one."
      - name: Show date and time
        run: date
